### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by pirakleous** [stklcode/node-red-contrib-huebridge#1]
Hello,

I am trying to add some sensors on my own witch echo. Checking the logs when i ask alexa to discover devices i can only see requests to api/:username/lights and I do not see any requests to api/:username/sensors.

From the [link](https://github.com/stklcode/node-red-contrib-huebridge/blob/master/lib/Sensors.js#L51-L61) i can see that you handle requests for sensors. Any hint on when alexa will call the api call for sensors as it always checks for lights?

Thanks

**Comment by stklcode** [comment]
The bridge emulation handles sensor requests, at least for two types (more are WIP, I just recently forked the project). They are available in compatible apps, so I assume the implementation is not too far from correct.

Sensors are available to the “user“, i.e. the Echo device in your case. However I‘ve never seen requests from Echo devices to the sensors API directly on device search without cloud connectivity.

**Comment by pirakleous** [comment]
Thanks for the update.

I tried to connect hue app with this bridge, it says to click the button and i inject a message to link button but the app cannot detect the bridge.

**Comment by stklcode** [comment]
I know, the official Hue app does not work at the moment. I’m investigating on how to achieve this.
Apps like “Hue Essentials“ do connect well.

**Comment by pirakleous** [comment]
Thank you. performing a kind of a debug i see an api request as /api/nouser/config then the app says that it found a new hub. when you click to add this hub it asks to click on the button of the hub. since there is no button i tried to send a payload to the "link button", but i do not see any other request coming from the app. it might be possible that the app is waiting for some kind of ssdp

**Comment by stklcode** [comment]
I've run some tcpdump analysis, too and came to the same conclusion.

UDP packages for SSDP are exchanged, _nouser_ API requested and silence.
I've compared the behavior to _diyHue_ (which works in that scenario). Apparently another advertisment is issued after _nouser_ request and the communication changes to HTTPS and the app sends the handshake _POST_ every second until linkbutton is _true_.

I'll probably find some time over the weekend to figure out a working solution to combine API and SSDP during handshake.
Self-signed HTTPS generation is already available locally, too.

**Comment by pirakleous** [comment]
I tested with Hue Essentials and it can find the hue bridge. What i am trying to achieve is to expose sensors/lights/switches and control them with alexa. When i ask alexa discover devices i see api calls to /api/:username/lights I am not sure if this is a limitation with alexa and it can only search for lights but it looks like more devices are supported. I dont know i only see api calls for lights. I tried to pass a response for lights and include a switch but that didnt work.

**Comment by stklcode** [comment]
As already said, I've never seen a single call to the `.../sensors/` endpoint from an Alexa device, not even to a real Philips Hue Bridge. It works fine with the Hue skill and connected cloud account (using a real bridge), but I don't even know if there is any support for local use from the Alexa side.
